name: pi
on:
  push:
    branches:    
      - main
jobs:
  push:
      runs-on: ${{ matrix.operating-system }}
      strategy:
        matrix:
          # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
          operating-system: ['ubuntu-22.04']
      steps:
      - uses: actions/checkout@v3 # Checking out the repo
      - name: Run with setup-python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          update-environment: true
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Install dependecies
        run: uv sync --frozen
      - name: Build
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          XMLRPC_PHP: ${{ secrets.XMLRPC_PHP }}
          IMAGE_HOSTING_URL: ${{ secrets.IMAGE_HOSTING_URL }}
          IMAGE_HOSTING_SECRET_TOKEN: ${{ secrets.IMAGE_HOSTING_SECRET_TOKEN }}
        run: uv run main.py
      - name: Commit and push if changed   # 将.md_sha1 README.md 更新到仓库
        run: |
          git diff
          git config --global user.email "zhaoolee@gmail.com"
          git config --global user.name "zhaoolee"
          git add .md_sha1 README.md
          git commit -m "Github Action auto Updated"
          git push
